### ISSUE TITLE
create basic UI

### ISSUE THREAD

**Issue by Qeolvdxu** [Qeolvdxu/ODTV#12]
A lot of this seems to be done, but its still good to keep track

**Comment by Qeolvdxu** [comment]
Any way we can have the pause and play button be the same button like on most video players? its not super great switching between pause and play with the cursor each time, but its not really a requirement from our client so....

**Comment by SleepySterling** [comment]
That's better from a UX standpoint, but I thought it would be easier programming-wise to have a separate play/pause button.  It's something we can change if we have additional time left over.

**Comment by SleepySterling** [comment]
Closing this. Most, if not all, of the GUI should be complete, aside from some minor changes.
